Create ko_KR.json
YimMenu/Translations pull request #116
Opened 2024-02-17 00:23 UTC by xenix4845

I have created a translation in Korean for the convenience of Korean users.

2024-02-17 03:07 UTC, gir489returns commented
[index.json](https://github.com/YimMenu/Translations/blob/master/index.json) needs to be updated with the Korean entry and the version number incremented. 

Can you also vouge that you wrote these yourself and did not use machine translation?

2024-02-17 03:11 UTC, xenix4845 commented
Words I don't know have been translated using a translator, but there seems to be no big problem in using them. However, if there is a translation problem, we will continue to update it.

2024-02-17 04:40 UTC, gir489returns commented
Some of the words you might've encountered might be specific to GTA V, this project itself, the cheating scene, or a combination of the 3. When I did the Russian translation, I tried to reference GTA itself for words I couldn't find a translation for. Like in Russian, there is no word for mod, I just used whatever GTA called upgrades.

For those words, I think it's best if you don't translate them and leave them as their original Latin-based text counterpart, even if that is wrong in Korean.

2024-02-17 09:58 UTC, xenix4845 commented
I used a translator to find difficult words during the translation process into Korean. However, for terms specific to GTA, I left them as they are or took measures like writing them phonetically, as I believe they need to be checked using YIMMENU to ensure they fit naturally. It would be helpful to test this translation first in YIMMENU, but unfortunately, Korean is not displayed there. Therefore, the translation needs approval first, and once officially applied, I can identify and address any issues.


I ask for your understanding that I am not an English speaker, so sometimes there may be grammar errors.

2024-02-17 14:09 UTC, Yimura commented
@xenix4845, you can modify the index.js file to include Korean. I’m not sure we support Korean characters in our fonts either.

2024-02-17 14:13 UTC, xenix4845 commented
@Yimura I hope it will be supported well without any problems.

2024-02-17 14:15 UTC, Yimura commented
> @Yimura I hope it will be supported well without any problems.

I meant on your local filesystem, you can modify the index.json file to include Korean and add your Korean json file as well. After which it should appear on the menu and allow you to load it.

2024-02-17 14:18 UTC, xenix4845 commented
> I meant on your local filesystem, you can modify the index.json file to include Korean and add your Korean json file as well. After which it should appear on the menu and allow you to load it.

When I tried it before, there was a problem that the letters were marked with question marks.

Ex: 한국어 -> ???

2024-02-17 14:22 UTC, xenix4845 commented
> > When I tried it before, there was a problem that the letters were marked with question marks.
> > 
> > Ex: 한국어 -> ???
> 
> That means we don’t support the Korean characters in YimMenu. We’ll have to take a look at adding perhaps.

We ask for Korean language support so that many Korean users can use it without language barriers.

2024-02-18 01:57 UTC, gir489returns commented
> We ask for Korean language support so that many Korean users can use it without language barriers.

What fonts do you know of on Windows that support Hangul?

2024-02-18 03:05 UTC, xenix4845 commented
> > We ask for Korean language support so that many Korean users can use it without language barriers.
> 
> What fonts do you know of on Windows that support Hangul?

A font called Malgun Gothic(맑은 고딕) supports Hangeul.

2024-02-18 04:12 UTC, gir489returns commented
@xenix4845 I have added a draft PR to the main project, that should detect when the Korean language is used by GTA itself, and then load a different font. Please test the DLL included with PR https://github.com/YimMenu/YimMenu/pull/2718 it should be in the comments from the builder bot.

2024-02-18 04:27 UTC, xenix4845 commented
I downloaded the file and tried running it, but the Korean still shows '???'.
And I don't think it's possible to check exactly because I can't use it in Korean in YIMMenu yet. Is there anything I'm doing wrong?

2024-02-18 06:38 UTC, gir489returns commented
> I downloaded the file and tried running it, but the Korean still shows '???'. And I don't think it's possible to check exactly because I can't use it in Korean in YIMMenu yet. Is there anything I'm doing wrong?

Can you post the cout.log from when you injected the test build?

2024-02-18 07:06 UTC, xenix4845 commented
[04:51:05.6867578][INFO/main.cpp:159] Yim's Menu Initializing
[04:51:05.6867950][INFO/main.cpp:160] Git Info
	Branch:	
	Hash:	38bb09ca4fa2c5a366c8c7429fbe7a7af67b829d
	Date:	Sun Feb 18 05:11:36 2024
[04:51:05.6869194][INFO/main.cpp:172] Windows 11 Pro Version 23H2 (OS Build 22631.3155)
[04:51:05.6895179][DEBUG/thread_pool.cpp:22] Resizing thread pool from 0 to 4
[04:51:05.6897929][INFO/main.cpp:180] Thread pool initialized.
[04:51:05.6927279][INFO/main.cpp:183] Settings Loaded.
[04:51:05.6927279][DEBUG/thread_pool.cpp:96] Thread 57940 executing settings.cpp:12
[04:51:05.6932538][INFO/pointers.hpp:94] GTA5 pointers cache is up to date, using it.
[04:51:05.6932774][INFO/pointers.cpp:1813] Loading pointers instance from cache
[04:51:05.6932793][INFO/pointers.cpp:1822] Pointers cache: Loading 216 fields from the cache
[04:51:05.6932871][DEBUG/module.cpp:50] Waiting for socialclub.dll...
[04:52:22.3327697][INFO/pointers.hpp:94] Social Club pointers cache is up to date, using it.
[04:52:22.3327856][INFO/pointers.cpp:1813] Loading pointers instance from cache
[04:52:22.3327883][INFO/pointers.cpp:1822] Pointers cache: Loading 5 fields from the cache
[04:52:22.3328213][INFO/main.cpp:186] Pointers initialized.
[04:52:22.3328250][WARN/main.cpp:190] Failed patching anticheat gameskeleton (injected too early?). Waiting 100ms and trying again
[04:52:22.4330518][WARN/main.cpp:190] Failed patching anticheat gameskeleton (injected too early?). Waiting 100ms and trying again
[04:52:22.5332557][WARN/main.cpp:190] Failed patching anticheat gameskeleton (injected too early?). Waiting 100ms and trying again
[04:52:22.6334882][INFO/main.cpp:193] Disabled anticheat gameskeleton.
[04:52:22.6336984][INFO/main.cpp:196] Byte Patch Manager initialized.
[04:52:22.9684147][INFO/main.cpp:199] Renderer initialized.
[04:52:23.1102254][INFO/main.cpp:203] Fiber pool initialized.
[04:52:23.1110674][INFO/main.cpp:206] HTTP Client initialized.
[04:52:23.5222863][INFO/main.cpp:209] Translation Service initialized.
[04:52:23.5348259][INFO/main.cpp:212] Hooking initialized.
[04:52:23.5386259][DEBUG/gta_data_service.cpp:160] Loading data from cache.
[04:52:23.5386334][INFO/gta_data_service.cpp:172] Loading 1051 peds from cache.
[04:52:23.5388909][INFO/gta_data_service.cpp:190] Loading 843 vehicles from cache.
[04:52:23.5390848][INFO/gta_data_service.cpp:207] Loading 119 weapons from cache.
[04:52:23.5390862][INFO/gta_data_service.cpp:208] Loading 380 weapon components from cache.
[04:52:23.5391038][DEBUG/gta_data_service.cpp:166] Loaded all data from cache.
[04:52:23.5436637][DEBUG/thread_pool.cpp:96] Thread 10388 executing player_database_service.cpp:285
[04:52:23.5437772][INFO/main.cpp:233] Registered service instances...
[04:52:23.5438894][INFO/main.cpp:254] Scripts registered.
[04:52:23.7073945][INFO/main.cpp:257] Hooking enabled.
[04:52:23.7074465][INFO/main.cpp:260] Dynamic native hooker initialized.
[04:52:23.7165454][FATAL/lua_module.cpp:299] 에임경고.lua failed to load: ...s\lont9\AppData\Roaming\YimMenu\scripts\에임경고.lua:91: syntax error near '+'
[04:52:23.7177756][INFO/main.cpp:264] Lua manager initialized.
[04:55:51.4346199][INFO/queue_dependency.cpp:63] Blocking AC Verifier 318b98
[04:55:51.5309465][INFO/queue_dependency.cpp:63] Blocking AC Verifier 9621f0
[04:55:51.5309998][INFO/queue_dependency.cpp:63] Blocking AC Verifier a668ec
[04:55:51.5313110][INFO/queue_dependency.cpp:63] Blocking AC Verifier 66f724
[04:55:51.5313187][INFO/queue_dependency.cpp:63] Blocking AC Verifier 66f74c
[04:55:51.5313533][INFO/queue_dependency.cpp:63] Blocking AC Verifier 66f774
[04:55:51.5313586][INFO/queue_dependency.cpp:63] Blocking AC Verifier 66f6fc
[04:55:51.5315583][INFO/queue_dependency.cpp:63] Blocking AC Verifier 335458
[04:55:51.5315734][INFO/queue_dependency.cpp:63] Blocking AC Verifier 335430
[04:55:51.5316066][INFO/queue_dependency.cpp:63] Blocking AC Verifier 4012b8
[04:55:51.5416961][INFO/queue_dependency.cpp:63] Blocking AC Verifier 45acf4
[04:55:51.5426311][INFO/queue_dependency.cpp:63] Blocking AC Verifier 459f38
[04:55:51.5426380][INFO/queue_dependency.cpp:63] Blocking AC Verifier 5ca880
[04:55:51.9542750][INFO/backend.cpp:53] Starting script: Self
[04:55:51.9542936][INFO/backend.cpp:78] Starting script: Weapons
[04:55:51.9543227][INFO/backend.cpp:101] Starting script: Vehicles
[04:55:51.9543343][INFO/backend.cpp:117] Starting script: Miscellaneous
[04:55:51.9543784][INFO/backend.cpp:138] Starting script: Remote
[04:55:51.9543868][INFO/backend.cpp:153] Starting script: Ls customs
[04:55:51.9543933][INFO/backend.cpp:165] Starting script: Rainbow paint
[04:55:51.9543957][INFO/backend.cpp:177] Starting script: Disable Control Action
[04:55:51.9544006][INFO/backend.cpp:190] Starting script: World
[04:55:51.9621676][INFO/tunables_service.cpp:36] Loading tunables from cache
[04:57:04.5010798][DEBUG/thread_pool.cpp:96] Thread 52144 executing view_settings.cpp:54
[04:57:06.2167675][WARN/translation_service.cpp:111] Failed to update 'ko_KR' language pack
[05:18:51.4247548][DEBUG/thread_pool.cpp:96] Thread 52144 executing view_settings.cpp:54
[05:18:53.0487897][WARN/translation_service.cpp:111] Failed to update 'ko_KR' language pack
[05:19:04.7083589][DEBUG/thread_pool.cpp:96] Thread 52144 executing translation_service.cpp:94
[05:19:04.7107464][INFO/translation_service.cpp:163] Translations for 'fr_FR' does not exist, downloading from https://raw.githubusercontent.com/YimMenu/Translations/master
[05:19:07.0125354][DEBUG/thread_pool.cpp:96] Thread 52144 executing translation_service.cpp:94
[05:19:08.3084478][DEBUG/thread_pool.cpp:96] Thread 52144 executing translation_service.cpp:94
[05:19:09.5425839][DEBUG/thread_pool.cpp:96] Thread 52144 executing translation_service.cpp:94
[05:19:10.8449050][DEBUG/thread_pool.cpp:96] Thread 52144 executing translation_service.cpp:94
[05:19:12.9424374][DEBUG/thread_pool.cpp:96] Thread 52144 executing translation_service.cpp:94
[05:19:12.9452228][INFO/translation_service.cpp:163] Translations for 'pt_BR' does not exist, downloading from https://raw.githubusercontent.com/YimMenu/Translations/master
[05:19:14.3757414][DEBUG/thread_pool.cpp:96] Thread 52144 executing translation_service.cpp:94
[05:19:14.3779836][INFO/translation_service.cpp:163] Translations for 'ru_RU' does not exist, downloading from https://raw.githubusercontent.com/YimMenu/Translations/master
[05:19:16.0555441][DEBUG/thread_pool.cpp:96] Thread 52144 executing translation_service.cpp:94
[05:19:18.5321899][DEBUG/thread_pool.cpp:96] Thread 52144 executing translation_service.cpp:94
[05:19:18.5345461][INFO/translation_service.cpp:163] Translations for 'zh_TW' does not exist, downloading from https://raw.githubusercontent.com/YimMenu/Translations/master
[05:19:25.1025702][DEBUG/thread_pool.cpp:96] Thread 52144 executing translation_service.cpp:94
[05:19:28.4259698][DEBUG/thread_pool.cpp:96] Thread 52144 executing translation_service.cpp:94
[05:19:31.2572780][INFO/main.cpp:272] Scripts unregistered.
[05:19:31.2586117][INFO/main.cpp:275] Lua manager uninitialized.
[05:19:31.4074924][INFO/main.cpp:278] Hooking disabled.
[05:19:31.4076419][INFO/main.cpp:281] Dynamic native hooker uninitialized.
[05:19:31.4076506][DEBUG/thread_pool.cpp:109] Thread 52144 exiting...
[05:19:31.4076518][DEBUG/thread_pool.cpp:109] Thread 57940 exiting...
[05:19:31.4076579][DEBUG/thread_pool.cpp:109] Thread 44536 exiting...
[05:19:31.5285147][DEBUG/thread_pool.cpp:109] Thread 10388 exiting...
[05:19:31.5289579][INFO/main.cpp:286] Destroyed thread pool.
[05:19:31.5289710][INFO/main.cpp:289] Script Connection Service reset.
[05:19:31.5303129][INFO/main.cpp:291] Tunables Service reset.
[05:19:31.5303232][INFO/main.cpp:293] Hotkey Service reset.
[05:19:31.5303267][INFO/main.cpp:295] Matchmaking Service reset.
[05:19:31.5305859][INFO/main.cpp:297] Player Database Service reset.
[05:19:31.5305890][INFO/main.cpp:299] API Service reset.
[05:19:31.5306361][INFO/main.cpp:301] Script Patcher Service reset.
[05:19:31.5306564][INFO/main. [...]

2024-02-18 23:39 UTC, gir489returns commented
The error is just complaining that it can't fetch ko_KR.json from our repo, because it doesn't exist yet.

https://github.com/YimMenu/YimMenu/pull/2718 I pushed another commit last night to output which language GTA is using, and which font it's trying to use. Please download the latest DLL from the ticket and post the log from its output.

2024-02-19 00:45 UTC, xenix4845 commented
[00:41:20.6825088][INFO/main.cpp:159] Yim's Menu Initializing
[00:41:20.6825394][INFO/main.cpp:160] Git Info
	Branch:	
	Hash:	38bb09ca4fa2c5a366c8c7429fbe7a7af67b829d
	Date:	Sun Feb 18 05:11:36 2024
[00:41:20.6827440][INFO/main.cpp:172] Windows 11 Pro Version 23H2 (OS Build 22631.3155)
[00:41:20.6852339][DEBUG/thread_pool.cpp:22] Resizing thread pool from 0 to 4
[00:41:20.6853852][INFO/main.cpp:180] Thread pool initialized.
[00:41:20.6879843][INFO/main.cpp:183] Settings Loaded.
[00:41:20.6879860][DEBUG/thread_pool.cpp:96] Thread 41428 executing settings.cpp:12
[00:41:20.6888827][INFO/pointers.hpp:94] GTA5 pointers cache is up to date, using it.
[00:41:20.6888981][INFO/pointers.cpp:1813] Loading pointers instance from cache
[00:41:20.6888993][INFO/pointers.cpp:1822] Pointers cache: Loading 216 fields from the cache
[00:41:20.6889064][DEBUG/module.cpp:50] Waiting for socialclub.dll...
[00:41:23.4059479][INFO/pointers.hpp:94] Social Club pointers cache is up to date, using it.
[00:41:23.4059686][INFO/pointers.cpp:1813] Loading pointers instance from cache
[00:41:23.4059718][INFO/pointers.cpp:1822] Pointers cache: Loading 5 fields from the cache
[00:41:23.4060461][INFO/main.cpp:186] Pointers initialized.
[00:41:23.4060561][WARN/main.cpp:190] Failed patching anticheat gameskeleton (injected too early?). Waiting 100ms and trying again
[00:41:23.5065133][WARN/main.cpp:190] Failed patching anticheat gameskeleton (injected too early?). Waiting 100ms and trying again
[00:41:23.6074087][WARN/main.cpp:190] Failed patching anticheat gameskeleton (injected too early?). Waiting 100ms and trying again
[00:41:23.7083082][WARN/main.cpp:190] Failed patching anticheat gameskeleton (injected too early?). Waiting 100ms and trying again
[00:41:23.8092117][INFO/main.cpp:193] Disabled anticheat gameskeleton.
[00:41:23.8094970][INFO/main.cpp:196] Byte Patch Manager initialized.
[00:41:24.1354697][INFO/main.cpp:199] Renderer initialized.
[00:41:24.3247684][INFO/main.cpp:203] Fiber pool initialized.
[00:41:24.3258561][INFO/main.cpp:206] HTTP Client initialized.
[00:41:24.8488838][INFO/main.cpp:209] Translation Service initialized.
[00:41:24.8604029][INFO/main.cpp:212] Hooking initialized.
[00:41:24.8670931][DEBUG/gta_data_service.cpp:160] Loading data from cache.
[00:41:24.8671035][INFO/gta_data_service.cpp:172] Loading 1051 peds from cache.
[00:41:24.8674074][INFO/gta_data_service.cpp:190] Loading 843 vehicles from cache.
[00:41:24.8676715][INFO/gta_data_service.cpp:207] Loading 119 weapons from cache.
[00:41:24.8676735][INFO/gta_data_service.cpp:208] Loading 380 weapon components from cache.
[00:41:24.8676867][DEBUG/gta_data_service.cpp:166] Loaded all data from cache.
[00:41:24.8811898][DEBUG/thread_pool.cpp:96] Thread 36996 executing player_database_service.cpp:285
[00:41:24.8813860][INFO/main.cpp:233] Registered service instances...
[00:41:24.8815341][INFO/main.cpp:254] Scripts registered.
[00:41:25.1109577][INFO/main.cpp:257] Hooking enabled.
[00:41:25.1109962][INFO/main.cpp:260] Dynamic native hooker initialized.
[00:41:25.1222792][FATAL/lua_module.cpp:299] 에임경고.lua failed to load: ...s\lont9\AppData\Roaming\YimMenu\scripts\에임경고.lua:91: syntax error near '+'
[00:41:25.1227013][INFO/main.cpp:264] Lua manager initialized.
[00:42:08.1551402][INFO/backend.cpp:53] Starting script: Self
[00:42:08.1551627][INFO/backend.cpp:78] Starting script: Weapons
[00:42:08.1551673][INFO/backend.cpp:101] Starting script: Vehicles
[00:42:08.1551752][INFO/backend.cpp:117] Starting script: Miscellaneous
[00:42:08.1552061][INFO/backend.cpp:138] Starting script: Remote
[00:42:08.1552091][INFO/backend.cpp:153] Starting script: Ls customs
[00:42:08.1552112][INFO/backend.cpp:165] Starting script: Rainbow paint
[00:42:08.1552133][INFO/backend.cpp:177] Starting script: Disable Control Action
[00:42:08.1552161][INFO/backend.cpp:190] Starting script: World
[00:42:08.1644184][INFO/tunables_service.cpp:36] Loading tunables from cache
[00:42:17.6714669][DEBUG/thread_pool.cpp:96] Thread 37796 executing view_settings.cpp:54
[00:43:10.1594328][INFO/queue_dependency.cpp:63] Blocking AC Verifier 9621f0
[00:43:10.1594717][INFO/queue_dependency.cpp:63] Blocking AC Verifier a668ec
[00:44:14.5202719][DEBUG/thread_pool.cpp:96] Thread 37796 executing view_settings.cpp:54


If there's a problem, I can't find Korean in the menu settings.

2024-02-19 00:48 UTC, gir489returns commented
I do not think you followed my instructions properly, as the log is incorrect.

`[00:47:31.1711787][INFO/main.cpp:159] Yim's Menu Initializing
[00:47:31.1711952][INFO/main.cpp:160] Git Info
        Branch:
        Hash:   275fd581d1762f423eb2fbb10ad3ddd2eaa341cc
        Date:   Sun Feb 18 07:42:45 2024
[00:47:31.1712448][INFO/main.cpp:172] Windows 11 Pro Version 23H2 (OS Build 22631.3155)
[00:47:31.1719639][DEBUG/thread_pool.cpp:22] Resizing thread pool from 0 to 4
[00:47:31.1720193][INFO/main.cpp:180] Thread pool initialized.
[00:47:31.1873930][INFO/main.cpp:183] Settings Loaded.
[00:47:31.1873988][DEBUG/thread_pool.cpp:96] Thread 10468 executing settings.cpp:12
[00:47:31.1917723][INFO/pointers.hpp:94] GTA5 pointers cache is up to date, using it.
[00:47:31.1917932][INFO/pointers.cpp:1813] Loading pointers instance from cache
[00:47:31.1917948][INFO/pointers.cpp:1822] Pointers cache: Loading 216 fields from the cache
[00:47:31.1918036][DEBUG/module.cpp:50] Waiting for socialclub.dll...
[00:47:31.1945105][INFO/pointers.hpp:94] Social Club pointers cache is up to date, using it.
[00:47:31.1945147][INFO/pointers.cpp:1813] Loading pointers instance from cache
[00:47:31.1945160][INFO/pointers.cpp:1822] Pointers cache: Loading 5 fields from the cache
[00:47:31.1945433][INFO/main.cpp:186] Pointers initialized.
[00:47:31.1945472][INFO/main.cpp:193] Disabled anticheat gameskeleton.
[00:47:31.1947141][INFO/main.cpp:196] Byte Patch Manager initialized.
[00:47:31.1952951][INFO/renderer.cpp:58] Language: 0 using font: "msyh.ttc"
[00:47:31.4328193][INFO/main.cpp:199] Renderer initialized.
[00:47:31.5195594][INFO/main.cpp:203] Fiber pool initialized.
[00:47:31.5246525][INFO/main.cpp:206] HTTP Client initialized.
[00:47:31.6355031][INFO/main.cpp:209] Translation Service initialized.
[00:47:31.6416910][INFO/main.cpp:212] Hooking initialized.
[00:47:31.6543916][DEBUG/gta_data_service.cpp:160] Loading data from cache.
[00:47:31.6543998][INFO/gta_data_service.cpp:172] Loading 1051 peds from cache.
[00:47:31.6545900][INFO/gta_data_service.cpp:190] Loading 843 vehicles from cache.
[00:47:31.6547680][INFO/gta_data_service.cpp:207] Loading 119 weapons from cache.
[00:47:31.6547717][INFO/gta_data_service.cpp:208] Loading 380 weapon components from cache.
[00:47:31.6547791][DEBUG/gta_data_service.cpp:166] Loaded all data from cache.
[00:47:31.6578858][DEBUG/thread_pool.cpp:96] Thread 29860 executing player_database_service.cpp:285
[00:47:31.6579399][INFO/main.cpp:233] Registered service instances...
[00:47:31.6579916][INFO/main.cpp:254] Scripts registered.
[00:47:31.7073809][INFO/main.cpp:257] Hooking enabled.
[00:47:31.7074143][INFO/main.cpp:260] Dynamic native hooker initialized.
[00:47:31.7685851][INFO/lua_module.cpp:304] Loaded CasinoPacino.lua
[00:47:31.7793434][INFO/lua_module.cpp:304] Loaded json.lua
[00:47:31.7991270][INFO/lua_module.cpp:304] Loaded Coords.lua
[00:47:31.8202950][INFO/lua_module.cpp:304] Loaded DailyCollectibles.lua
[00:47:31.8300750][INFO/lua_module.cpp:304] Loaded Util.lua
[00:47:31.8445952][INFO/lua_module.cpp:304] Loaded FullPistolReload.lua
[00:47:31.8599013][INFO/lua_module.cpp:304] Loaded FullSnacks.lua
[00:47:31.8794280][INFO/lua_module.cpp:304] Loaded InternetComputers.lua
[00:47:31.8970283][INFO/lua_module.cpp:304] Loaded minigamehack.lua
[00:47:31.9164389][INFO/lua_module.cpp:304] Loaded WasabiWords.lua
[00:47:31.9164938][INFO/main.cpp:264] Lua manager initialized.
`

Your build is from 5 o'clock and the one in the ticket is from 7. This is the log output from mine.

The line I am interested most in is this: 

`[00:47:31.1952951][INFO/renderer.cpp:58] Language: 0 using font: "msyh.ttc"`

This will tell me which language GTA is using, and which font Yim is trying to load.

2024-02-19 01:06 UTC, xenix4845 commented
[01:01:23.5855403][INFO/main.cpp:159] Yim's Menu Initializing
[01:01:23.5855689][INFO/main.cpp:160] Git Info
	Branch:	
	Hash:	275fd581d1762f423eb2fbb10ad3ddd2eaa341cc
	Date:	Sun Feb 18 07:42:45 2024
[01:01:23.5856967][INFO/main.cpp:172] Windows 11 Pro Version 23H2 (OS Build 22631.3155)
[01:01:23.5875078][DEBUG/thread_pool.cpp:22] Resizing thread pool from 0 to 4
[01:01:23.5876686][INFO/main.cpp:180] Thread pool initialized.
[01:01:23.5905082][DEBUG/thread_pool.cpp:96] Thread 39872 executing settings.cpp:12
[01:01:23.5905562][INFO/main.cpp:183] Settings Loaded.
[01:01:23.5918378][INFO/pointers.hpp:94] GTA5 pointers cache is up to date, using it.
[01:01:23.5918639][INFO/pointers.cpp:1813] Loading pointers instance from cache
[01:01:23.5918656][INFO/pointers.cpp:1822] Pointers cache: Loading 216 fields from the cache
[01:01:23.5918748][DEBUG/module.cpp:50] Waiting for socialclub.dll...
[01:01:26.2077862][INFO/pointers.hpp:94] Social Club pointers cache is up to date, using it.
[01:01:26.2078016][INFO/pointers.cpp:1813] Loading pointers instance from cache
[01:01:26.2078039][INFO/pointers.cpp:1822] Pointers cache: Loading 5 fields from the cache
[01:01:26.2078530][INFO/main.cpp:186] Pointers initialized.
[01:01:26.2078558][WARN/main.cpp:190] Failed patching anticheat gameskeleton (injected too early?). Waiting 100ms and trying again
[01:01:26.3085602][WARN/main.cpp:190] Failed patching anticheat gameskeleton (injected too early?). Waiting 100ms and trying again
[01:01:26.4092753][WARN/main.cpp:190] Failed patching anticheat gameskeleton (injected too early?). Waiting 100ms and trying again
[01:01:26.5095979][WARN/main.cpp:190] Failed patching anticheat gameskeleton (injected too early?). Waiting 100ms and trying again
[01:01:26.6104713][INFO/main.cpp:193] Disabled anticheat gameskeleton.
[01:01:26.6106821][INFO/main.cpp:196] Byte Patch Manager initialized.
[01:01:26.6118168][INFO/renderer.cpp:58] Language: 8 using font: "msyh.ttc"
[01:01:26.9786903][INFO/main.cpp:199] Renderer initialized.
[01:01:27.1200172][INFO/main.cpp:203] Fiber pool initialized.
[01:01:27.1210156][INFO/main.cpp:206] HTTP Client initialized.
[01:01:27.7127220][INFO/main.cpp:209] Translation Service initialized.
[01:01:27.7236639][INFO/main.cpp:212] Hooking initialized.
[01:01:27.7302484][DEBUG/gta_data_service.cpp:160] Loading data from cache.
[01:01:27.7302632][INFO/gta_data_service.cpp:172] Loading 1051 peds from cache.
[01:01:27.7305491][INFO/gta_data_service.cpp:190] Loading 843 vehicles from cache.
[01:01:27.7309035][INFO/gta_data_service.cpp:207] Loading 119 weapons from cache.
[01:01:27.7309085][INFO/gta_data_service.cpp:208] Loading 380 weapon components from cache.
[01:01:27.7309429][DEBUG/gta_data_service.cpp:166] Loaded all data from cache.
[01:01:27.7393755][DEBUG/thread_pool.cpp:96] Thread 32148 executing player_database_service.cpp:285
[01:01:27.7396591][INFO/main.cpp:233] Registered service instances...
[01:01:27.7398818][INFO/main.cpp:254] Scripts registered.
[01:01:27.9133753][INFO/main.cpp:257] Hooking enabled.
[01:01:27.9134512][INFO/main.cpp:260] Dynamic native hooker initialized.
[01:01:27.9249700][FATAL/lua_module.cpp:299] 에임경고.lua failed to load: ...s\lont9\AppData\Roaming\YimMenu\scripts\에임경고.lua:91: syntax error near '+'
[01:01:27.9254032][INFO/main.cpp:264] Lua manager initialized.
[01:02:11.3585584][INFO/backend.cpp:53] Starting script: Self
[01:02:11.3585740][INFO/backend.cpp:78] Starting script: Weapons
[01:02:11.3585922][INFO/backend.cpp:101] Starting script: Vehicles
[01:02:11.3586008][INFO/backend.cpp:117] Starting script: Miscellaneous
[01:02:11.3586321][INFO/backend.cpp:138] Starting script: Remote
[01:02:11.3586417][INFO/backend.cpp:153] Starting script: Ls customs
[01:02:11.3586456][INFO/backend.cpp:165] Starting script: Rainbow paint
[01:02:11.3586478][INFO/backend.cpp:177] Starting script: Disable Control Action
[01:02:11.3586504][INFO/backend.cpp:190] Starting script: World
[01:02:11.3682135][INFO/tunables_service.cpp:36] Loading tunables from cache
[01:02:12.3391054][DEBUG/thread_pool.cpp:96] Thread 32144 executing view_settings.cpp:54
[01:02:23.2572949][DEBUG/thread_pool.cpp:96] Thread 32144 executing view_settings.cpp:54
[01:02:59.1024102][INFO/queue_dependency.cpp:63] Blocking AC Verifier 318b98
[01:02:59.1032130][INFO/queue_dependency.cpp:63] Blocking AC Verifier 45acf4
[01:02:59.1032884][INFO/queue_dependency.cpp:63] Blocking AC Verifier 459f38
[01:02:59.1032920][INFO/queue_dependency.cpp:63] Blocking AC Verifier 5ca880
[01:02:59.1088149][INFO/queue_dependency.cpp:63] Blocking AC Verifier 66f724
[01:02:59.1088356][INFO/queue_dependency.cpp:63] Blocking AC Verifier 66f74c
[01:02:59.1112107][INFO/queue_dependency.cpp:63] Blocking AC Verifier 335458
[01:02:59.1112261][INFO/queue_dependency.cpp:63] Blocking AC Verifier 335430
[01:02:59.1112468][INFO/queue_dependency.cpp:63] Blocking AC Verifier 4012b8
[01:03:10.4546925][DEBUG/thread_pool.cpp:96] Thread 32144 executing view_settings.cpp:54
[01:03:17.1244929][INFO/queue_dependency.cpp:63] Blocking AC Verifier 9621f0
[01:03:17.1245277][INFO/queue_dependency.cpp:63] Blocking AC Verifier a668ec

Yes, when I tried it again, the above log was output now, but I couldn't find Korean in the menu setting.

2024-02-19 01:25 UTC, gir489returns commented
I have figured out the issue. I didn't properly set the font right if it detected a Korean GTA V instance.

2024-02-19 01:42 UTC, xenix4845 commented
> I have figured out the issue. I didn't properly set the font right if it detected a Korean GTA V instance.
> 
> Please try the new build included with the ticket [YimMenu/YimMenu#2718](https://github.com/YimMenu/YimMenu/pull/2718)

[01:40:15.2745022][INFO/main.cpp:159] Yim's Menu Initializing
[01:40:15.2745436][INFO/main.cpp:160] Git Info
	Branch:	
	Hash:	91568ea781c79d30a6414f110c9ecd139da1d710
	Date:	Mon Feb 19 02:09:18 2024
[01:40:15.2746879][INFO/main.cpp:172] Windows 11 Pro Version 23H2 (OS Build 22631.3155)
[01:40:15.2763375][DEBUG/thread_pool.cpp:22] Resizing thread pool from 0 to 4
[01:40:15.2764834][INFO/main.cpp:180] Thread pool initialized.
[01:40:15.2799249][INFO/main.cpp:183] Settings Loaded.
[01:40:15.2799252][DEBUG/thread_pool.cpp:96] Thread 14392 executing settings.cpp:12
[01:40:15.2804145][INFO/pointers.hpp:94] GTA5 pointers cache is up to date, using it.
[01:40:15.2804404][INFO/pointers.cpp:1812] Loading pointers instance from cache
[01:40:15.2804434][INFO/pointers.cpp:1821] Pointers cache: Loading 215 fields from the cache
[01:40:15.2804523][DEBUG/module.cpp:50] Waiting for socialclub.dll...
[01:40:15.2806585][INFO/pointers.hpp:94] Social Club pointers cache is up to date, using it.
[01:40:15.2806628][INFO/pointers.cpp:1812] Loading pointers instance from cache
[01:40:15.2806646][INFO/pointers.cpp:1821] Pointers cache: Loading 5 fields from the cache
[01:40:15.2807309][INFO/main.cpp:186] Pointers initialized.
[01:40:15.2807382][INFO/main.cpp:193] Disabled anticheat gameskeleton.
[01:40:15.2817369][FATAL/exception_handler.cpp:42] EXCEPTION_ACCESS_VIOLATION
Dumping modules:
GTA5.exe Base Address: 0x7FF752370000 Size: 67215872
ntdll.dll Base Address: 0x7FFB890B0000 Size: 1249280
KERNEL32.DLL Base Address: 0x7FFB87EB0000 Size: 528384
KERNELBASE.dll Base Address: 0x7FFB86A50000 Size: 1638400
USER32.dll Base Address: 0x7FFB884A0000 Size: 610304
win32u.dll Base Address: 0x7FFB868B0000 Size: 49152
GDI32.dll Base Address: 0x7FFB875C0000 Size: 57344
gdi32full.dll Base Address: 0x7FFB86670000 Size: 675840
msvcp_win.dll Base Address: 0x7FFB865D0000 Size: 335872
ucrtbase.dll Base Address: 0x7FFB86790000 Size: 798720
PSAPI.DLL Base Address: 0x7FFB88650000 Size: 4096
WS2_32.dll Base Address: 0x7FFB87490000 Size: 290816
VERSION.dll Base Address: 0x7FFB7E330000 Size: 12288
RPCRT4.dll Base Address: 0x7FFB87240000 Size: 880640
GFSDK_ShadowLib.win64.dll Base Address: 0x7FFAB9EB0000 Size: 96256
DSOUND.dll Base Address: 0x7FFAEC0C0000 Size: 491520
msvcrt.dll Base Address: 0x7FFB87FD0000 Size: 507904
CRYPT32.dll Base Address: 0x7FFB863F0000 Size: 1134592
WINTRUST.dll Base Address: 0x7FFB86560000 Size: 307200
advapi32.dll Base Address: 0x7FFB873C0000 Size: 442368
IMM32.dll Base Address: 0x7FFB88300000 Size: 126976
sechost.dll Base Address: 0x7FFB86E00000 Size: 458752
bink2w64.dll Base Address: 0x7FFABE130000 Size: 307712
bcrypt.dll Base Address: 0x7FFB869A0000 Size: 110592
ole32.dll Base Address: 0x7FFB88EB0000 Size: 909312
SHLWAPI.dll Base Address: 0x7FFB87E50000 Size: 212992
combase.dll Base Address: 0x7FFB86EB0000 Size: 2539520
SHELL32.dll Base Address: 0x7FFB875F0000 Size: 6852608
OLEAUT32.dll Base Address: 0x7FFB88110000 Size: 647168
WININET.dll Base Address: 0x7FFB60590000 Size: 2113536
WINMM.dll Base Address: 0x7FFB7CE50000 Size: 114688
MF.dll Base Address: 0x7FFB7DB80000 Size: 372736
msdmo.dll Base Address: 0x7FFB0FD20000 Size: 16384
shcore.dll Base Address: 0x7FFB88200000 Size: 684032
MFPlat.DLL Base Address: 0x7FFB7D320000 Size: 1503232
MFReadWrite.dll Base Address: 0x7FFB20630000 Size: 995328
PROPSYS.dll Base Address: 0x7FFB813A0000 Size: 692224
ResampleDmo.DLL Base Address: 0x7FFAEC000000 Size: 503808
d3d9.dll Base Address: 0x7FFB39210000 Size: 1306624
WTSAPI32.dll Base Address: 0x7FFB85290000 Size: 40960
D3DCOMPILER_43.dll Base Address: 0x7FFABD8A0000 Size: 2423296
XINPUT1_3.dll Base Address: 0x400000 Size: 85504
GFSDK_TXAA_AlphaResolve.win64.dll Base Address: 0x7FFB65C70000 Size: 48128
DINPUT8.dll Base Address: 0x7FFAEF180000 Size: 76288
SETUPAPI.dll Base Address: 0x7FFB88A30000 Size: 913408
IPHLPAPI.DLL Base Address: 0x7FFB84EE0000 Size: 122880
powrprof.dll Base Address: 0x7FFB85240000 Size: 77824
winmmbase.dll Base Address: 0x7FFB57DD0000 Size: 102400
d3dx9_43.dll Base Address: 0x7FFAB9C40000 Size: 2280960
cfgmgr32.dll Base Address: 0x7FFB860E0000 Size: 221184
dwmapi.dll Base Address: 0x7FFB82B60000 Size: 90112
OPENGL32.dll Base Address: 0x7FFAF0B00000 Size: 798720
MFCORE.DLL Base Address: 0x7FFB7D680000 Size: 3022848
dxcore.dll Base Address: 0x7FFB834D0000 Size: 139264
GLU32.dll Base Address: 0x7FFAFA7B0000 Size: 126976
UMPDC.dll Base Address: 0x7FFB85220000 Size: 36864
kernel.appcore.dll Base Address: 0x7FFB854E0000 Size: 36864
bcryptPrimitives.dll Base Address: 0x7FFB869D0000 Size: 376832
RTWorkQ.DLL Base Address: 0x7FFB7D2E0000 Size: 102400
MSASN1.dll Base Address: 0x7FFB86090000 Size: 36864
dinput8.dll Base Address: 0x7FFAEF1B0000 Size: 176128
inputhost.dll Base Address: 0x7FFB63150000 Size: 1540096
CoreMessaging.dll Base Address: 0x7FFB82120000 Size: 864256
CRYPTBASE.DLL Base Address: 0x7FFB85C80000 Size: 12288
MSVCP140.dll Base Address: 0x7FFB5A130000 Size: 340480
dbghelp.dll Base Address: 0x7FFB835F0000 Size: 1646592
D3DCOMPILER_47.dll Base Address: 0x7FFB81510000 Size: 3043328
VCRUNTIME140.dll Base Address: 0x7FFB5A430000 Size: 73728
VCRUNTIME140_1.dll Base Address: 0x7FFB5A420000 Size: 15360
CRYPTSP.dll Base Address: 0x7FFB85CA0000 Size: 57344
secur32.dll Base Address: 0x7FFB852B0000 Size: 12288
SSPICLI.DLL Base Address: 0x7FFB85740000 Size: 126976
HeapAdjuster.asi Base Address: 0x7FFB4AD90000 Size: 130560
OpenIV.asi Base Address: 0x7FFB62780000 Size: 80384
PackfileLimitAdjuster.asi Base Address: 0x7FFB48430000 Size: 212480
sdk_legacy_led_x64.dll Base Address: 0x7FFB3FC00000 Size: 2554880
ZLIB1.dll Base Address: 0x7FFB7DC50000 Size: 54784
rsaenh.dll Base Address: 0x7FFB85440000 Size: 147456
mswsock.dll Base Address: 0x7FFB85950000 Size: 331776
windows.storage.dll Base Address: 0x7FFB84310000 Size: 7032832
wintypes.dll Base Address: 0x7FFB841D0000 Size: 544768
dbgcore.DLL Base Address: 0x7FFB68C70000 Size: 131072
d3d12.dll Base Address: 0x7FFB483F0000 Size: 102400
EOSSDK-Win64-Shipping.dll Base Address: 0x7FFAF9230000 Size: 7229440
WLDAP32.dll Base Address: 0x7FFB87360000 Size: 274432
Normaliz.dll Base Address: 0x7FFB87480000 Size: 4096
WINHTTP.dll Base Address: 0x7FFB7E430000 Size: 987136
uxtheme.dll Base Address: 0x7FFB828F0000 Size: 425984
clbcatq.dll Base Address: 0x7FFB87510000 Size: 471040
dxdiagn.dll Base Address: 0x7FFB3FB90000 Size: 253952
d3d11.dll Base Address: 0x7FFB83830000 Size: 1867776
DEVOBJ.dll Base Address: 0x7FFB860B0000 Size: 110592
dxgi.dll Base Address: 0x7FFB83A90000 Size: 651264
WMICLNT.dll Base Address: 0x7FFB80570000 Size: 32768
wbemprox.dll Base Address: 0x7FFB70D00000 Size: 28672
wbemcomn.dll Base Address: 0x7FFB70C80000 Size: 311296
NSI.dll Base Address: 0x7FFB881F0000 Size: 8192
dhcpcsvc6.DLL Base Address: 0x7FFB7E580000 Size: 28672
dhcpcsvc.DLL Base Address: 0x7FFB7E2C0000 Size: 69632
wbemsvc.dll Base Address: 0x7FFB79760000 Size: 8192
fastprox.dll Base Address: 0x7FFB797B0000 Size: 708608
amsi.dll Base Address: 0x7FFB78970000 Size: 57344
USERENV.dll Base Address: 0x7FFB859F0000 Size: 102400
profapi.dll Base Address: 0x7FFB86320000 Size: 90112
antimalware_provider64.dll Base Address: 0x7FFB40370000 Size: 653824
directxdatabasehelper.dll Base Address: 0x7FFB80D80000 Size: 196608
napinsp.dll Base Address: 0x7FFB519A0000 Size: 53248
pnrpnsp.dll Base Address: 0x7FFB51980000 Size: 69632
DNSAPI.dll Base Address: 0x7FFB84F50000 Size: 737280
winrnr.dll Base Address: 0x7FFB51960000 Size: 32768
wshbth.dll Base Address: 0x7FFB7CDA0000 Size: 45056
nlansp_c.dll Base Address: 0x7FFB51930000 Size: 81920
mdnsNSP.dll Base Address: 0x67260000 Size: 91136
nvapi64.dll Base Address: 0x7FFB6B8E0000 Size: 5629440
cryptnet.dll Base Address: 0x7FFB7B9E0000 Size: 139264
drvstore.dll Base Address: 0x7FFB7A830000 Size: 1044 [...]

2024-02-19 04:14 UTC, gir489returns commented
![image](https://github.com/YimMenu/Translations/assets/100792176/7623ab11-c847-4e78-923b-0cfa8501ab5e)

I figured out the issue, it was a multitude of things. Please try the build from https://github.com/YimMenu/YimMenu/pull/2718 again.

2024-02-19 04:31 UTC, xenix4845 commented
![스크린샷 2024-02-19 132855](https://github.com/YimMenu/Translations/assets/156365851/830573ab-3a3f-4de0-ba13-0aebfe56625c)

I just downloaded it and tried running it, but I don't think I can see the Korean font properly.

2024-02-19 04:32 UTC, gir489returns commented
The bot just finished compiling my latest commit 1 minute ago, try that one.

2024-02-19 04:33 UTC, xenix4845 commented
OK, I'll try once the bot completes the task.

2024-02-19 04:38 UTC, gir489returns commented
![image](https://github.com/YimMenu/Translations/assets/100792176/bdf6eaae-607b-446b-a191-2d0343839404)

@xenix4845 Does this look correct? This was done with my local build spoofing the language of GTA to Korean and using your translation file.

2024-02-19 04:41 UTC, xenix4845 commented
Yes, that's right. I can see Korean clearly. Could you tell me how I can apply the Korean translation and review it?

2024-02-19 04:44 UTC, gir489returns commented
> Yes, that's right. I can see Korean clearly. Could you tell me how I can apply the Korean translation and review it?

Pulling your translation repo into the translation folder un AppData/YimMenu should "update" it to show the Korean language you added.

2024-02-19 04:47 UTC, xenix4845 commented
> > Yes, that's right. I can see Korean clearly. Could you tell me how I can apply the Korean translation and review it?
> 
> Pulling your translation repo into the translation folder un AppData/YimMenu should "update" it to show the Korean language you added.

I didn't understand well. Can you tell me in detail about the method?

2024-02-19 04:47 UTC, gir489returns commented
> > > Yes, that's right. I can see Korean clearly. Could you tell me how I can apply the Korean translation and review it?
> > 
> > 
> > Pulling your translation repo into the translation folder un AppData/YimMenu should "update" it to show the Korean language you added.
> 
> I didn't understand well. Can you tell me in detail about the method?

Just copy the ko_KR.json file into appdata/yimmenu/translations and then in index.json change selected_language from en_US to ko_KR.

2024-02-19 04:49 UTC, xenix4845 commented
> > > > Yes, that's right. I can see Korean clearly. Could you tell me how I can apply the Korean translation and review it?
> > > 
> > > 
> > > Pulling your translation repo into the translation folder un AppData/YimMenu should "update" it to show the Korean language you added.
> > 
> > 
> > I didn't understand well. Can you tell me in detail about the method?
> 
> Just copy the ko_KR.json file into appdata/yimmenu/translations and then in index.json change selected_language from en_US to ko_KR.

It's been successful, and thank you for letting me know. 
Can you tell me when the translation I uploaded will be officially approved?

2024-02-19 04:51 UTC, gir489returns commented
> It's been successful, and thank you for letting me know. Can you tell me when the translation I uploaded will be officially approved?

I marked the PR ready for review. Once the internal code review process has been completed, it will be merged.

2024-02-19 09:49 UTC, Yimura requested changes

2024-02-19 09:49 UTC, Yimura commented on index.json
> +            "name": "한국어 (KR)",
Maybe this should be changed to normal characters as the font will not be loaded and thus only be showing "???".

```json
"name": "Korean (KR)",
```

This change is in-case we ever decide to add the dynamic font loading feature into YimMenu and you possibly might not have the font loaded. I believe most people either know their language written in English or phonological written form of their language in ASCII/UTF8.

@gir489returns, I'd be happy to hear your opinion on this, it ties in with the comment I made on YimMenu/YimMenu#2718.

2024-02-19 09:51 UTC, Yimura commented
> ![image](https://private-user-images.githubusercontent.com/156365851/305843161-eff57b63-30d8-435d-8692-44c6d533b8fc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgzMzY0OTcsIm5iZiI6MTcwODMzNjE5NywicGF0aCI6Ii8xNTYzNjU4NTEvMzA1ODQzMTYxLWVmZjU3YjYzLTMwZDgtNDM1ZC04NjkyLTQ0YzZkNTMzYjhmYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIxOVQwOTQ5NTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zM2RjMWQ5NmFjZjk2MDllOGE2ZjI2ZjgyN2JiYTE1MDk0OGFjZDY5YmFkZThkZGViZTNhMWM1NWVmZTgxYWMyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Hy67hXYPT-Pzqbl7qVRcpfre3yPBvT1Ous1Hr9p7hoE) I want to translate this part but I can't. What should I do?

That text is honestly a long time inside joke and should be removed.

2024-02-19 10:37 UTC, Yimura commented
PR got auto closed by the merge to add Korean font support to the game.

2024-02-19 11:53 UTC, xenix4845 commented on index.json
> +            "name": "한국어 (KR)",
I don't think it's a bad idea to write it in Korean instead of '한국어'.

2024-02-19 15:36 UTC, merged