Update french translation
YimMenu/Translations pull request #123
Opened 2024-03-10 20:48 UTC by Genetik57

Big update of the French translation file from scratch based on the en_US.json file

2024-03-10 22:21 UTC, xiaoxiao921 submitted a review, later dismissed

2024-03-11 11:22 UTC, gir489returns requested changes

2024-03-11 11:22 UTC, gir489returns commented on index.json
> +{
You changed the entire file. Revert and do again.

2024-03-11 14:30 UTC, Yimura approved these changes

2024-03-11 14:30 UTC, merged