translations for
YimMenu/Translations pull request #186
Opened 2024-07-18 21:58 UTC by CringeArab

Translations for [YimMenu#3380](https://github.com/YimMenu/YimMenu/pull/3380)

2024-07-19 12:17 UTC, gir489returns requested changes
BACKEND_LOOPED_WEAPONS_AIM_ONLY_AT_PLAYER doesn’t match the form used in AT ENEMY key (different падеж, idk how to translate it)
DESTROY_PERSONAL_VEHICLE doesn’t have any mention that vehicle is personal. 
PED_TYPE_PROSTITUTE has an interesting translation, it matches just fine, but if to be pedantic it should’ve been «Проститутки», it might not fit again, idk. Or you worked in some translation studio where you are discouraged from using direct swears even if original had them lmao.
TSE_FREEZE_MISMATCH is “install mismatch of script event”

2024-07-19 13:33 UTC, gir489returns requested changes

2024-07-19 13:33 UTC, gir489returns commented on en_US.json
> +  "TSE_FREEZE_MISMATCH": "Install Mismatch of Script Event",
This entry makes no sense, what are you installing?

2024-07-20 01:11 UTC, gir489returns commented on en_US.json
> +  "TSE_FREEZE_MISMATCH": "Install Mismatch of Script Event",
Fix it please.

2024-07-20 01:13 UTC, gir489returns commented on ru_RU.json
> +  "TSE_SENDER_MISMATCH": "Установка несоответствия скриптового события",
Make this TSE Эмиттер несоответствие. Double check it, my Russian is trash.

2024-07-20 10:30 UTC, Yimura approved these changes

2024-07-20 10:30 UTC, merged