Change spelling of 2 UI Elements
YimMenu/Translations pull request #20
Opened 2023-03-18 16:24 UTC by Rxann

I pretty much changed the spelling of 2 UI items to fit proper grammar.

Speedo meter -> Speedometer
TP in PV -> TP Into PV

I am not used to PR's so sorry if I did something wrong.

2023-03-27 14:10 UTC, Yimura requested changes

2023-03-27 14:10 UTC, Yimura commented on en_US.json
Please indent the whole file with 4 spaces instead of 2.

2023-03-28 20:32 UTC, Rxann commented
I just made a commit, tell me if this is what you would like to see or something else

2023-04-01 16:01 UTC, Yimura approved these changes

2023-04-01 16:02 UTC, merged