Spanish added
YimMenu/Translations pull request #29
Opened 2023-04-11 14:15 UTC by Papela

This pr adds the translation for the Spanish of Spain

2023-04-11 14:55 UTC, DaniTRDev commented
The overall translation seems good to me, although there's a few of them that are weird. I'll submit a review as soon as I can. 
PD: are you from Spain?

2023-04-11 15:14 UTC, Papela commented
Yes I'm from Spain. What happens is that to lighten the work a bit, I have been using the translator a bit together with the AI.

2023-04-12 15:05 UTC, DaniTRDev commented
He añadido algunas correciones, despues seguire. Cuando puedas intenta corregir las traducciones que marque o si se te ocurre algo mejor dimelo por mensaje.

2023-04-12 17:20 UTC, DayibBaba commented
> He añadido algunas correciones, despues seguire. Cuando puedas intenta corregir las traducciones que marque o si se te ocurre algo mejor dimelo por mensaje.

"I have added some corrections, then I will continue. When you can, try to correct the translations that I marked, or if you think of something better, let me know by message."

-Translated by chatgpt

2023-04-13 11:42 UTC, DaniTRDev requested changes
Overall transalation is good. I've included a few changes for a better understanding. There's a few cases that I did not mark although they are quite weird for a native Spanish speaker, but I can't think on a better translation without writting a lot of words, which would result in a massive GUI size increase.

2023-04-13 11:42 UTC, DaniTRDev commented on es_ES.json
> +    "KICK_ALL_FROM_INTERIORS": "Patear a todos los de Interiores",
'Expulsar jugadores de interiores'

2023-04-13 11:42 UTC, DaniTRDev commented on es_ES.json
> +    "TP_ALL_TO_APARTMENT": "TP Todo Al Apartamento",
'Teletransportar a todos al apartamento'.

2023-04-13 11:42 UTC, DaniTRDev commented on es_ES.json
> +    "TP_ALL_TO_WAREHOUSE": "TP Todo al almacén",
'Teletransportar a todos al almacén'.

2023-04-13 11:42 UTC, DaniTRDev commented on es_ES.json
> +    "TP_ALL_TO_DARTS": "TP Todo a los Dardos",
'Teletransportar a todos a la sala de dardos'.

2023-04-13 11:42 UTC, DaniTRDev commented on es_ES.json
> +    "TP_ALL_TO_MULTI_FLOOR_GARAGE": "TP Todo A Garaje De Varias Plantas",
I add it here because I saw there are multiple translation using the same incorrect scheme. Correct it with 'Teletransportar a todos a... '.

2023-04-13 11:42 UTC, DaniTRDev commented on es_ES.json
> +    "EVENT_STARTER": "Inicio del evento",
'Iniciador del evento'.

2023-04-13 11:42 UTC, DaniTRDev commented on es_ES.json
> +    "DISABLE_PEDS": "Peatones inhabilitados",
'Eliminar NPCs del juego'.

2023-04-13 11:42 UTC, DaniTRDev commented on es_ES.json
> +    "DISABLE_TRAFFIC": "Desactivar tráfico",
'Eliminar vehículos del juego'.

2023-04-13 11:42 UTC, DaniTRDev commented on es_ES.json
> +    "SEAT_CHANGER": "Cambiador de asientos",
'Cambiar de asiento'.

2023-04-13 11:42 UTC, DaniTRDev commented on es_ES.json
> +    "TO_WAYPOINT": "A la baliza",
'Al punto fijado en el mapa'.

2023-04-13 11:42 UTC, DaniTRDev commented on es_ES.json
> +    "TROLL": "Troll",
Check these TP translations please.

2023-04-13 11:42 UTC, DaniTRDev commented on es_ES.json
> +    "BOUNTY": "Generoso",
'Recompensa'.

2023-04-13 11:42 UTC, DaniTRDev commented on es_ES.json
> +    "BLIPS": "Blips:",
'Iconos del mapa'.

2023-04-13 11:42 UTC, DaniTRDev commented on es_ES.json
> +    "VEHICLE_FLY": "Vehículo Fly",
'Hacer volar al vehículo'.

2023-04-13 16:40 UTC, DaniTRDev requested changes

2023-04-13 19:08 UTC, Papela commented
> He añadido algunas correciones, despues seguire. Cuando puedas intenta corregir las traducciones que marque o si se te ocurre algo mejor dimelo por mensaje.

He añadido mas correciones, pero creo que todavia me quedan mas por resolver, mañana seguire.🙃

2023-04-13 19:26 UTC, GeopJr commented on es_ES.json
> +    "REMOTE_KICK_BREAKUP_PLAYER": "¡Alguien ha intentado de expulsar a otro jugador a distancia!",
English: `Someone tried to breakup kick {} remotely!`

Your translation is missing the `{}` (which will be the name of the player trying to kick you)

2023-04-14 16:50 UTC, GeopJr commented on index.json
> +    "version": 15,
Pretty sure version shouldn't be bumped as this is a new translation

cc: @Yimura

2023-04-14 17:27 UTC, DaniTRDev approved these changes
Approved, thanks for contributting to YimMenu! <3

2023-04-14 17:28 UTC, DaniTRDev approved these changes

2023-04-14 17:46 UTC, GeopJr approved these changes

2023-04-14 18:16 UTC, merged